version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    build: .
    platform: linux/amd64
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      NODE_ENV: production
    command: ['npm', 'start']
volumes:
  db_data:
    driver: local
